# Generated by Django 2.0.2 on 2018-02-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurers.RiskType'),
            preserve_default=False,
        ),
    ]
