# Generated by Django 2.0.2 on 2018-02-25 21:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0002_riskfield_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskfield',
            old_name='risk_text',
            new_name='field_name',
        ),
        migrations.RenameField(
            model_name='risktype',
            old_name='name',
            new_name='risk_name',
        ),
        migrations.AddField(
            model_name='riskfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('enum', 'enum')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risktype',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 21, 7, 25, 902769, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
