# Generated by Django 2.0.2 on 2018-03-14 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0003_auto_20180225_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskfield',
            options={'ordering': ['value']},
        ),
        migrations.AddField(
            model_name='riskfield',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='insurers.RiskType'),
        ),
        migrations.AlterUniqueTogether(
            name='riskfield',
            unique_together={('risk', 'value')},
        ),
    ]
